### ISSUE TITLE
Saving and loading l3TrainingOLS 

### ISSUE THREAD

**Issue by wandell** [scienstanford/L3reverse#1]
I am not sure how we load and store the trained structures with their data.  The simple 
save('filename','l3t') method does not work as I expected.  I guess we need to create something like an l3t.save function?

And then we need to be able to read in what was saved with l3TrainOLS('filename')?  Is that right?

**Comment by hjiang36** [comment]
I thought save('filename', 'l3t') should work. We can check together.

One practical issue for saving the training class directly is that l3t.l3c usually contains training data. This could make l3t to be several hundred MB large. To avoid that, call l3t.l3c.clearData() first and then save the object.

I like the idea to have save and create method. I'll add them soon.

**Comment by wandell** [comment]
HJ wrote a 'save' option.  We also discovered that clearing the data does work, as above, and if we do not clear there appears to be a Matlab bug or some failure to understand on our part. But in the presence of the data, nothing is saved.
